puts "The students of my cohort at Makers Academy"
puts "------------------"
puts "Roy Gardiner"
puts "Berta Gutierrez"
puts "Megan Folsom"
puts "Rolando Barbella"
puts "James Hunter"
puts "Abraham Thomas"
puts "Jorja Tracy Hung"
puts "Colin Frankish"
puts "Andrey Krahmal"
puts "Ayaz Goulamabasse"
puts "Biwek Shrestha"
puts "Mihai-Liviu Cojocar"
puts "Makis Otman"
puts "Nabin Rai"
puts "Peter Saxton"
puts "Kalle Malmiharju"
